[project]
name = "reinvent"  # Normalized according to https://packaging.python.org/en/latest/specifications/name-normalization/
#version = "4.0.0"  # Dynamic.
description = "Reinvent 4"
authors = [{name = "AstraZeneca"}]
maintainers = [{name = "Hannes Löffler", email = "hannes.loeffler@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
keywords = [
  "reinvent",
  "de novo drug design",
  "ai",
  "artificial intelligence",
  "molecules",
  "molecule generation",
  "linker design",
  "generative ai",
  "chemistry",
  "medicinal chemistry",
  "computational chemistry",
  "cheminformatics",
]
classifiers = [
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: MacOS",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Topic :: Scientific/Engineering :: Chemistry",
  "Topic :: Scientific/Engineering :: Medical Science Apps.",
  "Typing :: Typed",
]

dynamic = ["version"]

# We go quite defensive and add upper bounds,
# in case major version updates break backward compatibility.
dependencies = []

[project.scripts]
reinvent = "reinvent.Reinvent:main"


# FIXME: change urls for public release.
[project.urls]
homepage = "https://github.com/MolecularAI"
repository = "https://github.com/MolecularAI/Reinvent.git"
public-reposibory = "https://github.com/MolecularAI/Reinvent.git"  # Switch to a new repo?


[tool.setuptools]
include-package-data = true


[tool.setuptools.dynamic.version]
attr = "reinvent.version.__version__"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = [".", "configs"]
include = ["reinvent*"]
namespaces = true


[tool.setuptools.package-data]
"*" = ["*.pkl.gz"]


[tool.black]
line-length = 100
